dist: trusty

language: python

python:
  - 3.6

git:
  depth: 1

install:
  - pip3 install --upgrade pip
  - nvm install node

script:
  - nvm use node
  - make init
  - make install-dev
  - make front
  - make tests
  - make lint