dist: trusty

language: python

python:
  - 3.6

git:
  depth: 1

install:
  - pip3 install pipenv
  - nvm install node
  - export PATH=$PATH:./node/modules/.bin/


script:
  - nvm use default
  - make init
  - make front
  - make lint